### ISSUE TITLE
Error in step 1 qtlpoly vignette

### ISSUE THREAD

**Issue by peterbourke** [guilherme-pereira/QTLpoly#1]
Hi,

Running the qtlpoly vignette step 1 

genoprob <- lapply(maps, calc_genoprob)

causes the following error:

_Error in if (length(input.map$info$mrk.names) == 2 & input.map$info$mrk.names[1] ==  : 
  argument is of length zero_

Closer inspection reveals that within each element of maps and then info, there is no object mrk.names. I haven't added any files as this should be reproducible by running the vignette.

Best regards,
Peter

**Comment by guilherme-pereira** [comment]
Hi Peter,

Thank you for your question. The example data object has been recently updated, but the tutorial hasn't - I apologize for that. Please use 

> `data(maps.hexafake)`
> `genoprob <- lapply(maps.hexafake, calc_genoprob)`

from mappoly package instead of `data(maps)` from qtlpoly. We'll update it in our package, too. You may find minor differences regarding position and estimates of detected QTL, but you should be able to run the tutorial for now.

Best regards,

Gui.

**Comment by peterbourke** [comment]
That works fine, many thanks.
-P
